name: pepperfry
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  http: ^1.0.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/pepperfrysplash.png"

  android_12:
    image: assets/pepperfrysplash.png

flutter:
  uses-material-design: true
  assets:
    - assets/
